
NORMAL = "NORMAL"
ALIAS_ACEPTADO = "ALIAS_ACEPTADO"
ALIAS_RECHAZADO = "ALIAS_RECHAZADO"
MENSAJE = "MENSAJE"
SERVIDOR = "SERVIDOR"
PARTIDA_INICIADA = "PARTIDA_INICIADA"
PARTIDA_FINALIZADA = "PARTIDA_FINALIZADA"
