{
    "solicitarIp": "Please, enter the Server IP: ",
    "solicitarPuerto": "Please, enter the Server Port: ",
    "mensajeBienvenida": "Conected, welcome to UBlackJack!",
    "errorConexion": "An error ocurred during the connection: ",
    "conexionPerdida": "Lost connection to server",
    "errorComando": "Error sending command",
    "conectar": "Connect",
    "pedir": "Pedir",
    "ingresar": "Found",
    "apostar": "Bet",
    "doblar": "Double",
    "separar": "Split",
    "plantarse": "Stand",
    "mensaje": "Message",
    "enviar": "Send",
    "salir": "Exit",
    "jugar": "Play",
    "bienvenido": "Welcome ",
    "bienvenidoAlJuego": "Welcome to the game. Enter your name by the soy <name> command.",
    "ingresarMontoMayorCero": "You must to enter a value greather than 0",
    "ingresarSaldo": "You muse to enter an ammount to continue",
    "comandoDesconocido": "Command unknown",
    "errorFaltaIdentificarse": "You have to identify yourself first by the soy <name> command",
    "errorYaTeConozco": "I already know you. Your name is {0}, not {1}",
    "juegaLaBanca": "Now the bank will playa",
    "bancaMuestraCartaOculta": "The bank will show its hidden card",
    "solicitarApuesta": "enter your bet",
    "usuarioAbandono": "The user {0} has left the room",
    "timerEmpiezaElJuego": "The game will begin in {0} seconds",
    "jugadorSeUnio": "{0} has joined the game",
    "jugadorFondeo": "{0} has founded",
    "hayRondaActiva": "There is an active round, once finished you will be joined automatically. You can leave the wait by closing the connection.",
    "iniciarCuentaRegresiva": "We will start the countdown to start the game",
    "finalizacionCuentaRegresiva": "After the countdown is over, the game begins",
    "bancaTiene": "The bank has {0}",
    "corazones": "Hearts",
    "picas": "Pike",
    "diamantes": "Diamonds",
    "treboles": "Clover",
    "As": "Ace",
    "Dos": "Two",
    "Tres": "Three",
    "Cuatro": "Four",
    "Cinco": "Five",
    "Seis": "Six",
    "Siete": "Seven",
    "Ocho": "Eight",
    "Nueve": "Nine",
    "Diez": "Ten",
    "Jack": "Jack",
    "Reina": "Queen",
    "Rey": "King",
    "compuestoPor": "{0} formed by {1}",
    "descripcionCarta": "{0} of {1}",
    "cartaBocaAbajo": "and a card face down",
    "esTurnoDe": "It is {0} turn",
    "dineroInsuficiente": "You have not enough money",
    "apuestaYaRealizada": "You have already placed a bet",
    "ganador": "Congratulations! You Won!",
    "empate": "It is a draw, you got back what you bet!",
    "perdedor": "You lost against bank!",
    "noEsTurno": "It is not your turn",
    "puntajeObtenido": "{0} has got {1}",
    "jugadorPerdio": "{0} has lost, with a score of {1}"
}