{
    "solicitarIp": "Por favor ingresa la IP del servidor: ",
    "solicitarPuerto": "Por favor ingresa el puerto del servidor: ",
    "mensajeBienvenida": "Conectado, bienvenido a UBlackJack!",
    "errorConexion": "Ocurrio un error al conectarse con el servidor: ",
    "conexionPerdida": "Se perdio la conexion con el servidor",
    "errorComando": "Error al enviar el comando",
    "conectar": "Conectar",
    "pedir": "PEDIR",
    "ingresar": "INGRESAR",
    "apostar": "APOSTAR",
    "doblar": "DOBLAR",
    "separar": "SEPARAR",
    "plantarse": "PLANTARSE",
    "mensaje": "MENSAJE",
    "enviar": "ENVIAR",
    "salir": "SALIR",
    "jugar": "Jugar",
    "bienvenido": "Bienvenido ",
    "bienvenidoAlJuego": "Bienvenido al juego. Ingresa tu nombre con el comando soy <nombre>.",
    "ingresarMontoMayorCero": "Tenes que ingresar un monto mayor a 0",
    "ingresarSaldo": "Debes ingresar un saldo para iniciar",
    "comandoDesconocido": "No conozco ese comando",
    "errorFaltaIdentificarse": "Primero tenes que identificarte con el comando soy <nombre>",
    "errorNombreRepetido": "Ese nombre ya esta tomado",
    "errorYaTeConozco": "Ya te conozco. Te llamas {0}, no {1}",
    "juegaLaBanca": "Ahora jugara la banca",
    "bancaMuestraCartaOculta": "La banca mostrara su carta oculta",
    "solicitarApuesta": "ingresa tu apuesta",
    "usuarioAbandono": "El usuario {0} abandono la sala",
    "timerEmpiezaElJuego": "Empieza el juego en {0} segundos",
    "jugadorSeUnio": "{0} se unio al juego",
    "jugadorFondeo": "{0} ha ingresado dinero",
    "hayRondaActiva": "Hay una ronda activa, una vez finalizada se te unira automaticamente. Puedes irte de la espera cerrando la conexion.",
    "iniciarCuentaRegresiva": "Iniciaremos cuenta regresiva para iniciar el juego",
    "finalizacionCuentaRegresiva": "Una vez finalizada la cuenta regresiva, comenzara la partida",
    "bancaTiene": "La banca tiene {0}",
    "corazones": "Corazones",
    "picas": "Picas",
    "diamantes": "Diamantes",
    "treboles": "Treboles",
    "As" : "As",
    "Dos": "Dos",
    "Tres": "Tres",
    "Cuatro": "Cuatro",
    "Cinco": "Cinco",
    "Seis": "Seis",
    "Siete": "Siete",
    "Ocho": "Ocho",
    "Nueve": "Nueve",
    "Diez": "Diez",
    "Jack": "Jack",
    "Reina": "Reina",
    "Rey": "Rey",
    "compuestoPor": "{0} compuestos por {1}",
    "descripcionCarta": "{0} de {1}",
    "cartaBocaAbajo": "y una carta boca abajo",
    "esTurnoDe": "Es el turno de {0}",
    "dineroInsuficiente": "No tienes el dinero suficiente",
    "apuestaYaRealizada": "Ya realizaste la apuesta de esta mano",
    "ganador": "Felicitaciones! Ganaste!",
    "empate": "Es un empate, recuperaste lo aposado!",
    "perdedor": "Perdiste contra la banca!",
    "noEsTurno": "No es tu turno",
    "puntajeObtenido": "{0} ha obtenido {1}",
    "jugadorPerdio": "{0} perdio con un puntaje de {1}",
    "detalleApuesta": "Hiciste una apuesta de ${0}. Tu saldo actual es de ${1}",
    "tuMano": "Tu mano es: {0}",
    "partidaFinalizada": "Partida Finalizada",
    "banca": "Banca",
    "errorNombreIgualBanca": "No te podes llamar igual que la Banca",
    "nombreVacio": "Debe ingresar un nombre para iniciar",
    "jugadorYaExiste": "Ya existe un jugador con ese nombre, ingrese uno diferente",
    "partidaIniciada": "Partida Iniciada"
}